---
title: "\"Finally\" kann nicht außerhalb einer Try-Anweisung verwendet werden."
ms.date: 07/20/2015
f1_keywords:
- vbc30382
- bc30382
helpviewer_keywords:
- BC30382
ms.assetid: 0314d8d2-18bc-4bbd-858c-0a18408b52fd
ms.openlocfilehash: 60f02c9000e99c6f1b91fb5f0e2929c4e696e549
ms.sourcegitcommit: f8c270376ed905f6a8896ce0fe25b4f4b38ff498
ms.translationtype: MT
ms.contentlocale: de-DE
ms.lasthandoff: 06/04/2020
ms.locfileid: "84403731"
---
# <a name="finally-cannot-appear-outside-a-try-statement"></a>"Finally" kann nicht außerhalb einer Try-Anweisung verwendet werden.
`Finally` wird zum Beenden eines `Try...Catch...Finally` -Blocks verwendet und kann daher nur einmal am Ende des Blocks angegeben werden. Entweder ist `Finally`unnötig, oder die `Finally` -Anweisung befindet sich außerhalb des entsprechenden `Try` -Blocks.  
  
 **Fehler-ID:** BC30382  
  
## <a name="to-correct-this-error"></a>So beheben Sie diesen Fehler  
  
1. Suchen und entfernen Sie die unnötige `Finally` -Anweisung.  
  
2. Verschieben Sie die `Finally` -Anweisung an die gewünschte Position im Code.  
  
## <a name="see-also"></a>Weitere Informationen

- [Try...Catch...Finally-Anweisung](../language-reference/statements/try-catch-finally-statement.md)
