---
title: Der Catch-Block wird niemals erreicht; "<exception>" wird oben in der gleichen Try-Anweisung behandelt
ms.date: 07/20/2015
f1_keywords:
- bc42031
- vbc42031
helpviewer_keywords:
- BC42031
ms.assetid: 7d15597c-5988-42ea-a853-63cbf78faaf3
ms.openlocfilehash: 987a509b4b099a0a1f728f55dfb2b35a8770af3f
ms.sourcegitcommit: f8c270376ed905f6a8896ce0fe25b4f4b38ff498
ms.translationtype: MT
ms.contentlocale: de-DE
ms.lasthandoff: 06/04/2020
ms.locfileid: "84395479"
---
# <a name="catch-block-never-reached-exception-handled-above-in-the-same-try-statement"></a>Der Catch-Block wird niemals erreicht; "\<exception>" wird oben in der gleichen Try-Anweisung behandelt
Ein `Catch` -Block im Code kann nicht erreicht werden, weil er in einem vorhergehenden `Try` -Block behandelt wird.  
  
Standardmäßig ist diese Meldung eine Warnung. Weitere Informationen zum Ausblenden von Warnungen oder zum Behandeln von Warnungen als Fehler finden Sie unter [Configuring Warnings in Visual Basic](/visualstudio/ide/configuring-warnings-in-visual-basic).
  
 **Fehler-ID:** BC42031  
  
## <a name="to-correct-this-error"></a>So beheben Sie diesen Fehler  
  
- Entfernen Sie die redundante Anweisung.  
  
## <a name="see-also"></a>Weitere Informationen

- [Verwenden des try/catch-Blocks zum Abfangen von Ausnahmen](../../standard/exceptions/how-to-use-the-try-catch-block-to-catch-exceptions.md)
- [Verwenden benutzergefilterter Ausnahmehandler](../../standard/exceptions/using-user-filtered-exception-handlers.md)
- [Try...Catch...Finally-Anweisung](../language-reference/statements/try-catch-finally-statement.md)
