---
title: Ausnahmen und Ausnahmebehandlung – C#-Programmierhandbuch
ms.date: 07/20/2015
helpviewer_keywords:
- exception handling [C#]
- exceptions [C#]
- C# language, exceptions
ms.assetid: 0001887f-4fa2-47e2-8034-2819477e2344
ms.openlocfilehash: 0ba123fa9f9aacd0876f07bdf3ae7bb9159a6834
ms.sourcegitcommit: a241301495a84cc8c64fe972330d16edd619868b
ms.translationtype: HT
ms.contentlocale: de-DE
ms.lasthandoff: 06/01/2020
ms.locfileid: "84241707"
---
# <a name="exceptions-and-exception-handling-c-programming-guide"></a><span data-ttu-id="951fb-102">Ausnahmen und Ausnahmebehandlung (C#-Programmierhandbuch)</span><span class="sxs-lookup"><span data-stu-id="951fb-102">Exceptions and Exception Handling (C# Programming Guide)</span></span>

<span data-ttu-id="951fb-103">Die C#-Funktionen zur Ausnahmebehandlung helfen Ihnen dabei, unerwartete oder außergewöhnliche Situationen zu verarbeiten, die beim Ausführen von Programmen auftreten können.</span><span class="sxs-lookup"><span data-stu-id="951fb-103">The C# language's exception handling features help you deal with any unexpected or exceptional situations that occur when a program is running.</span></span> <span data-ttu-id="951fb-104">Die Ausnahmebehandlung verwendet die Schlüsselwörter `try`, `catch` und `finally`, um Aktionen zu testen, die möglicherweise nicht erfolgreich sind, um Fehler zu behandeln, wenn Sie entscheiden, dass dies vernünftig ist, und um später Ressourcen zu bereinigen.</span><span class="sxs-lookup"><span data-stu-id="951fb-104">Exception handling uses the `try`, `catch`, and `finally` keywords to try actions that may not succeed, to handle failures when you decide that it is reasonable to do so, and to clean up resources afterward.</span></span> <span data-ttu-id="951fb-105">Ausnahmen können von der Common Language Runtime (CLR), von .NET bzw. anderen Drittanbieterbibliotheken oder vom Anwendungscode generiert werden.</span><span class="sxs-lookup"><span data-stu-id="951fb-105">Exceptions can be generated by the common language runtime (CLR), by .NET or third-party libraries, or by application code.</span></span> <span data-ttu-id="951fb-106">Ausnahmen werden mit dem Schlüsselwort `throw` erstellt.</span><span class="sxs-lookup"><span data-stu-id="951fb-106">Exceptions are created by using the `throw` keyword.</span></span>

<span data-ttu-id="951fb-107">In vielen Fällen wird eine Ausnahme nicht von einer Methode ausgelöst, die von Ihrem Code direkt aufgerufen wurde, sondern von einer anderen Methode weiter unten in der Aufrufliste.</span><span class="sxs-lookup"><span data-stu-id="951fb-107">In many cases, an exception may be thrown not by a method that your code has called directly, but by another method further down in the call stack.</span></span> <span data-ttu-id="951fb-108">In diesem Fall entlädt die CLR die Liste, sucht nach einer Methode mit einem `catch`-Block für den spezifischen Ausnahmetyp und führt den ersten gefundenen `catch`-Block aus.</span><span class="sxs-lookup"><span data-stu-id="951fb-108">When this happens, the CLR will unwind the stack, looking for a method with a `catch` block for the specific exception type, and it will execute the first such `catch` block that if finds.</span></span> <span data-ttu-id="951fb-109">Wenn kein geeigneter `catch`-Block in der Aufrufliste gefunden wird, beendet die CLR den Prozess und zeigt eine Meldung für den Benutzer an.</span><span class="sxs-lookup"><span data-stu-id="951fb-109">If it finds no appropriate `catch` block anywhere in the call stack, it will terminate the process and display a message to the user.</span></span>

<span data-ttu-id="951fb-110">In diesem Beispiel testet eine Methode, ob eine Division durch Null möglich ist, und fängt den Fehler ab.</span><span class="sxs-lookup"><span data-stu-id="951fb-110">In this example, a method tests for division by zero and catches the error.</span></span> <span data-ttu-id="951fb-111">Ohne Ausnahmebehandlung würde dieses Programm mit dem Fehler **DivideByZeroException wurde nicht behandelt** beendet.</span><span class="sxs-lookup"><span data-stu-id="951fb-111">Without the exception handling, this program would terminate with a **DivideByZeroException was unhandled** error.</span></span>

[!code-csharp[csProgGuideExceptions#18](~/samples/snippets/csharp/VS_Snippets_VBCSharp/csProgGuideExceptions/CS/Exceptions.cs#18)]

## <a name="exceptions-overview"></a><span data-ttu-id="951fb-112">Übersicht über Ausnahmen</span><span class="sxs-lookup"><span data-stu-id="951fb-112">Exceptions Overview</span></span>

<span data-ttu-id="951fb-113">Ausnahmen weisen folgende Eigenschaften auf:</span><span class="sxs-lookup"><span data-stu-id="951fb-113">Exceptions have the following properties:</span></span>

- <span data-ttu-id="951fb-114">Bei Ausnahmen handelt es sich um Typen, die alle letztlich von `System.Exception` abgeleitet werden.</span><span class="sxs-lookup"><span data-stu-id="951fb-114">Exceptions are types that all ultimately derive from `System.Exception`.</span></span>
- <span data-ttu-id="951fb-115">Verwenden Sie einen `try`-Block um die Anweisungen, die möglicherweise Ausnahmen auslösen.</span><span class="sxs-lookup"><span data-stu-id="951fb-115">Use a `try` block around the statements that might throw exceptions.</span></span>
- <span data-ttu-id="951fb-116">Sobald eine Ausnahme im `try`-Block auftritt, springt der Steuerungsfluss zum ersten zugeordneten Ausnahmehandler, der sich an einer beliebigen Stelle in der Aufrufliste befindet.</span><span class="sxs-lookup"><span data-stu-id="951fb-116">Once an exception occurs in the `try` block, the flow of control jumps to the first associated exception handler that is present anywhere in the call stack.</span></span> <span data-ttu-id="951fb-117">In C# wird das Schlüsselwort `catch` zum Definieren eines Ausnahmehandlers verwendet.</span><span class="sxs-lookup"><span data-stu-id="951fb-117">In C#, the `catch` keyword is used to define an exception handler.</span></span>
- <span data-ttu-id="951fb-118">Wenn für eine bestimmte Ausnahme kein Ausnahmehandler vorhanden ist, beendet das Programm die Ausführung mit einer Fehlermeldung.</span><span class="sxs-lookup"><span data-stu-id="951fb-118">If no exception handler for a given exception is present, the program stops executing with an error message.</span></span>
- <span data-ttu-id="951fb-119">Fangen Sie Ausnahmen nur dann ab, wenn Sie sie behandeln und die Anwendung in einem bekannten Zustand belassen können.</span><span class="sxs-lookup"><span data-stu-id="951fb-119">Do not catch an exception unless you can handle it and leave the application in a known state.</span></span> <span data-ttu-id="951fb-120">Wenn Sie `System.Exception` abfangen, lösen Sie diese mithilfe des Schlüsselworts `throw` am Ende des `catch`-Blocks erneut aus.</span><span class="sxs-lookup"><span data-stu-id="951fb-120">If you catch `System.Exception`, re-throw it using the `throw` keyword at the end of the `catch` block.</span></span>
- <span data-ttu-id="951fb-121">Wenn ein `catch`-Block eine Ausnahmevariable definiert, können Sie diese verwenden, um weitere Informationen zum Typ der aufgetretenen Ausnahme abzurufen.</span><span class="sxs-lookup"><span data-stu-id="951fb-121">If a `catch` block defines an exception variable, you can use it to obtain more information about the type of exception that occurred.</span></span>
- <span data-ttu-id="951fb-122">Ausnahmen können von einem Programm mithilfe des Schlüsselworts `throw` explizit generiert werden.</span><span class="sxs-lookup"><span data-stu-id="951fb-122">Exceptions can be explicitly generated by a program by using the `throw` keyword.</span></span>
- <span data-ttu-id="951fb-123">Ausnahmeobjekte enthalten detaillierte Informationen über den Fehler, z.B. den Zustand der Aufrufliste und eine Textbeschreibung des Fehlers.</span><span class="sxs-lookup"><span data-stu-id="951fb-123">Exception objects contain detailed information about the error, such as the state of the call stack and a text description of the error.</span></span>
- <span data-ttu-id="951fb-124">Code in einem `finally`-Block wird auch dann ausgeführt, wenn eine Ausnahme ausgelöst wurde.</span><span class="sxs-lookup"><span data-stu-id="951fb-124">Code in a `finally` block is executed even if an exception is thrown.</span></span> <span data-ttu-id="951fb-125">Verwenden Sie einen `finally`-Block, um Ressourcen freizugeben, beispielsweise um Streams oder Dateien zu schließen, die im `try`-Block geöffnet wurden.</span><span class="sxs-lookup"><span data-stu-id="951fb-125">Use a `finally` block to release resources, for example to close any streams or files that were opened in the `try` block.</span></span>
- <span data-ttu-id="951fb-126">Zusätzlich zum strukturierten Win32-Mechanismus zur Ausnahmebehandlung wurden in .NET verwaltete Ausnahmen implementiert.</span><span class="sxs-lookup"><span data-stu-id="951fb-126">Managed exceptions in .NET are implemented on top of the Win32 structured exception handling mechanism.</span></span> <span data-ttu-id="951fb-127">Weitere Informationen finden Sie unter [Structured Exception Handling (C/C++)](/cpp/cpp/structured-exception-handling-c-cpp) (Strukturierte Ausnahmebehandlung [C/C++]) und [A Crash Course on the Depths of Win32 Structured Exception Handling](http://bytepointer.com/resources/pietrek_crash_course_depths_of_win32_seh.htm) (Schnellkurs zu den Details der strukturierten Win32-Ausnahmebehandlung).</span><span class="sxs-lookup"><span data-stu-id="951fb-127">For more information, see [Structured Exception Handling (C/C++)](/cpp/cpp/structured-exception-handling-c-cpp) and [A Crash Course on the Depths of Win32 Structured Exception Handling](http://bytepointer.com/resources/pietrek_crash_course_depths_of_win32_seh.htm).</span></span>

## <a name="related-sections"></a><span data-ttu-id="951fb-128">Verwandte Abschnitte</span><span class="sxs-lookup"><span data-stu-id="951fb-128">Related Sections</span></span>

<span data-ttu-id="951fb-129">Weitere Informationen zu Ausnahmen und zur Ausnahmebehandlung finden Sie in den folgenden Artikeln:</span><span class="sxs-lookup"><span data-stu-id="951fb-129">See the following articles for more information about exceptions and exception handling:</span></span>

- [<span data-ttu-id="951fb-130">Verwenden von Ausnahmen</span><span class="sxs-lookup"><span data-stu-id="951fb-130">Using Exceptions</span></span>](using-exceptions.md)
- [<span data-ttu-id="951fb-131">Ausnahmebehandlung</span><span class="sxs-lookup"><span data-stu-id="951fb-131">Exception Handling</span></span>](exception-handling.md)
- [<span data-ttu-id="951fb-132">Erstellen und Auslösen von Ausnahmen</span><span class="sxs-lookup"><span data-stu-id="951fb-132">Creating and Throwing Exceptions</span></span>](creating-and-throwing-exceptions.md)
- [<span data-ttu-id="951fb-133">Vom Compiler generierte Ausnahmen</span><span class="sxs-lookup"><span data-stu-id="951fb-133">Compiler-Generated Exceptions</span></span>](compiler-generated-exceptions.md)
- [<span data-ttu-id="951fb-134">Behandeln einer Ausnahme mit „try/catch“ (C#-Programmierhandbuch)</span><span class="sxs-lookup"><span data-stu-id="951fb-134">How to handle an exception using try/catch (C# Programming Guide)</span></span>](how-to-handle-an-exception-using-try-catch.md)
- [<span data-ttu-id="951fb-135">Ausführen von Bereinigungscode mit „finally“</span><span class="sxs-lookup"><span data-stu-id="951fb-135">How to execute cleanup code using finally</span></span>](how-to-execute-cleanup-code-using-finally.md)
- [<span data-ttu-id="951fb-136">Abfangen einer Nicht-CLS-Ausnahme</span><span class="sxs-lookup"><span data-stu-id="951fb-136">How to catch a non-CLS exception</span></span>](how-to-catch-a-non-cls-exception.md)

## <a name="c-language-specification"></a><span data-ttu-id="951fb-137">C#-Programmiersprachenspezifikation</span><span class="sxs-lookup"><span data-stu-id="951fb-137">C# Language Specification</span></span>

<span data-ttu-id="951fb-138">Weitere Informationen erhalten Sie unter [Ausnahmen](~/_csharplang/spec/exceptions.md) in der [C#-Sprachspezifikation](/dotnet/csharp/language-reference/language-specification/introduction).</span><span class="sxs-lookup"><span data-stu-id="951fb-138">For more information, see [Exceptions](~/_csharplang/spec/exceptions.md) in the [C# Language Specification](/dotnet/csharp/language-reference/language-specification/introduction).</span></span> <span data-ttu-id="951fb-139">Die Sprachspezifikation ist die verbindliche Quelle für die Syntax und Verwendung von C#.</span><span class="sxs-lookup"><span data-stu-id="951fb-139">The language specification is the definitive source for C# syntax and usage.</span></span>

## <a name="see-also"></a><span data-ttu-id="951fb-140">Siehe auch</span><span class="sxs-lookup"><span data-stu-id="951fb-140">See also</span></span>

- <xref:System.SystemException>
- [<span data-ttu-id="951fb-141">C#-Programmierhandbuch</span><span class="sxs-lookup"><span data-stu-id="951fb-141">C# Programming Guide</span></span>](../index.md)
- [<span data-ttu-id="951fb-142">C#-Schlüsselwörter</span><span class="sxs-lookup"><span data-stu-id="951fb-142">C# Keywords</span></span>](../../language-reference/keywords/index.md)
- [<span data-ttu-id="951fb-143">throw</span><span class="sxs-lookup"><span data-stu-id="951fb-143">throw</span></span>](../../language-reference/keywords/throw.md)
- [<span data-ttu-id="951fb-144">try-catch</span><span class="sxs-lookup"><span data-stu-id="951fb-144">try-catch</span></span>](../../language-reference/keywords/try-catch.md)
- [<span data-ttu-id="951fb-145">try-finally</span><span class="sxs-lookup"><span data-stu-id="951fb-145">try-finally</span></span>](../../language-reference/keywords/try-finally.md)
- [<span data-ttu-id="951fb-146">try-catch-finally</span><span class="sxs-lookup"><span data-stu-id="951fb-146">try-catch-finally</span></span>](../../language-reference/keywords/try-catch-finally.md)
- [<span data-ttu-id="951fb-147">Ausnahmen</span><span class="sxs-lookup"><span data-stu-id="951fb-147">Exceptions</span></span>](../../../standard/exceptions/index.md)
